name: i ♥ nerd
description: 创意编程营养补给站
avatar: /assets/svg/logo.svg

footer-links:
  dribbble:
  github:
  linkedin:
  facebook:
  flickr:
  instagram:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  email:
  weibo:
  wechat:


duoshuo: inerdcc
disqus: onlylemi
google_analytics: UA-77283988-1

url: ''
enforce_ssl: ''

baseurl: ""
url: "http://inerd.cc"

markdown: kramdown
highlighter: rouge
permalink: /:title/

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    coderay_line_numbers: inline

version: v1.1.0

sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
